In [1]:
l = [ 234, 23, 43, 234 ]

In [2]:
l[1:]

[23, 43, 234]

In [3]:
l[0:2]

[234, 23]

In [4]:
l[::2]

[234, 43]

In [5]:
#------

In [9]:
import numpy as np
a = np.array([546, 215, -1234, 44, 514])

In [10]:
a

array([  546,   215, -1234,    44,   514])

In [11]:
a[2:]

array([-1234,    44,   514])

In [14]:
b = a[2:]

In [15]:
b

array([-1234,    44,   514])

In [16]:
b[0]

-1234

In [17]:
b[:] = 111

In [18]:
b

array([111, 111, 111])

In [19]:
a

array([546, 215, 111, 111, 111])

In [20]:
c = a.copy()

In [21]:
c

array([546, 215, 111, 111, 111])

In [22]:
c[0] = 0

In [23]:
c

array([  0, 215, 111, 111, 111])

In [24]:
a

array([546, 215, 111, 111, 111])